# Dev conf

services:
  backend:
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/?authSource=admin&directConnection=true

  frontend:
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
