version: "3.8"

# This file is automatically loaded by docker-compose for local development
# It overrides settings from docker-compose.yml

services:
  backend:
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/?authSource=admin&directConnection=true

  frontend:
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
